### ISSUE TITLE
Make this project a CDS Plugin Package

### ISSUE THREAD

**Issue by gregorwolf** [geert-janklaps/cds-launchpad-plugin#10]
Unfortunately the documentation at [cds-plugins](https://cap.cloud.sap/docs/node.js/cds-plugins) is not yet released. But the GitHub repository for Capire is now online. So [cds-plugins.md](https://github.com/cap-js/docs/blob/main/node.js/cds-plugins.md) can be checked there. We also can follow how the [cds-plugin-ui5](https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/cds-plugin-ui5) implement it.

**Comment by geert-janklaps** [comment]
This one was also in my mind, great idea. I just need to go through the documentation and see what is required to change the project to a real cds-plugin.

**Comment by geert-janklaps** [comment]
New major release is now a real CAP plugin thanks to @schiwekM! 🥇
