### ISSUE TITLE
update do README to reflect current version

### ISSUE THREAD

**Issue by ghost** [geert-janklaps/cds-launchpad-plugin#15]
Hi,

the README should be updated to reflect the current state.

Cause the setup has changed:
* with using of the cds plugin system - the setup in server.js ist not required
* the option/setting for the launchpad have moved to cds.env...

regards
Norbert

**Comment by geert-janklaps** [comment]
Hi Norbert,

Documentation is now up to date.

Best regards,
Geert-Jan
