### ISSUE TITLE
Use ui5.sap.com instead of sapui5.hana.ondemand.com

### ISSUE THREAD

**Issue by gregorwolf** [geert-janklaps/cds-launchpad-plugin#20]
Hi @geert-janklaps,

I would suggest to follow [Short and Powerful: Convenient URLs for SAPUI5/OpenUI5 CDN](https://blogs.sap.com/2022/07/20/short-and-powerful-convenient-urls-for-sapui5-openui5-cdn/) and use ui5.sap.com instead of sapui5.hana.ondemand.com.

Best Regards
Gregor

**Comment by geert-janklaps** [comment]
Hi @gregorwolf,

Sounds like a good idea, I'll do the change somewhere around the weekend. (I have limited availability today & tomorrow)

Cheers,
Geert-Jan
