### ISSUE TITLE
TypeError: content.replace is not a function

### ISSUE THREAD

**Issue by ghost** [geert-janklaps/cds-launchpad-plugin#22]
node_modules\cds-launchpad-plugin\src\index.ts:74:39

Shows sometimes and somitemens not...
Cause is that:
https://github.com/geert-janklaps/cds-launchpad-plugin/blob/c1ff2e19b371f2a5821491c3ebae8e1266b2c0e3/dist/index.js#L87

Sometime ```content``` is of type bytestream.
For me a single .toString() does the trick.

Am I the only one?

@fabiantschirschnitz

**Comment by GoWale** [comment]
Should be fixed with: version 2.1.3.

See change in PR: https://github.com/geert-janklaps/cds-launchpad-plugin/pull/19
