### ISSUE TITLE
Allow setting launchpad as default page

### ISSUE THREAD

**Issue by gregorwolf** [geert-janklaps/cds-launchpad-plugin#23]
Hi @geert-janklaps,

maybe I've missed it in the documentation. Is there an option to define the launchpad that is by default available at /$launchpad as the default page (index.html)?

Best Regards
Gregor

**Comment by geert-janklaps** [comment]
Hi @gregorwolf,

I've just pushed a new version of the launchpad plugin (2.1.5), this allows you to replace the default page by setting the existing basePath parameter to "/".

![image](https://github.com/geert-janklaps/cds-launchpad-plugin/assets/2744548/5ac34ce0-991f-4183-a81c-426c0edd7177)

Cheers,
Geert-Jan
