### ISSUE TITLE
Tile duplicated

### ISSUE THREAD

**Issue by Felipe-Renck** [geert-janklaps/cds-launchpad-plugin#47]
Hi.
I have 4 CAP apps in the same project.
<img width="510" alt="image" src="https://github.com/geert-janklaps/cds-launchpad-plugin/assets/7826007/294aeea8-ea06-48fa-ad3a-ec40b4d797fb">

When I open the launchpad, 5 tiles are displayed instead of 4, the last one is duplicated. 
<img width="1051" alt="image" src="https://github.com/geert-janklaps/cds-launchpad-plugin/assets/7826007/a6ddecbc-09df-4d49-9496-991ce6789009">

**cds-launchpad-plugin v2.2.0
node v18.19.0**

How can I fix it?

Thanks.

**Comment by gregorwolf** [comment]
Maybe the Exam app has multiple crossNavigation intents maintained?
