### ISSUE TITLE
Adjust launchpad template to allow configuration of renderers

### ISSUE THREAD

**Issue by gregorwolf** [geert-janklaps/cds-launchpad-plugin#7]
Hi @geert-janklaps,

what do you think about adding a posibility to configure the renderers section in the template. In this example:

https://github.com/gregorwolf/bookshop-demo/blob/main/app/webapp/fiori-ui5-1.106.html#L12

you see how I've disabled the search functionality to avoid requests to InA and ESH_SEARCH_SRV.

CU
Gregor

**Comment by geert-janklaps** [comment]
Hi @gregorwolf,

I think this is a great idea, I also noticed the calls being made. Although I didn't notice I could disable them :)

Maybe, just thinking out loud, it would be better to disable them by default? (And enable them through manual configuration as you suggest?)
I don't really think there is a use case for these calls in the context of testing our apps locally?

Cheers,
Geert-Jan
